@echo off
echo Starting Tailwind CSS Watcher...
echo Moving to theme directory...
cd themes/blowfish
echo Running Tailwind CLI...
npx tailwindcss -c ./tailwind.config.js -i ./assets/css/main.css -o ../../assets/css/compiled/main.css -w